version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - gosec
    - misspell
    - unconvert
    - unparam
  disable:
    - depguard
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (io.Closer).Close
    gosec:
      excludes:
        - G104
        - G304
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - core/wasm/policy
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/OpenNHP/opennhp
  exclusions:
    generated: lax
    paths:
      - core/wasm/policy
      - third_party$
      - builtin$
      - examples$
