FROM opennhp-base:latest AS builder

FROM ubuntu:20.04  AS runtime
ENV DEBIAN_FRONTEND=noninteractive

COPY --from=builder /nhp-server/release/nhp-agent /nhp-agent 

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["/nhp-agent/nhp-agentd run"]