FROM opennhp-base:latest  AS builder

WORKDIR /nhp-server

COPY . .

RUN echo "Building for architecture: ${TARGETARCH}"
## 
ENV GOPROXY=https://goproxy.cn,direct

RUN cd /nhp-server && cat Makefile && make init agentd test

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y  wget \
    ca-certificates \
    iptables \
    tcpdump \
    clang \
    ipset \
    git \
    curl \
    telnet \
    && rm -rf /var/lib/apt/lists/* 
    
RUN mv /nhp-server/release/nhp-agent /nhp-agent

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["/nhp-agent/nhp-agentd run"]