
[http]
  [http.routers]
    #
    # hqdata-opennhp-cn
    #
    [http.routers.router-hqdata-opennhp-cn]
      entryPoints = ["web"]
      #rule = "Host(`*`)"
      rule = "PathPrefix(`/`)"
      middlewares = ["HQDATAMiddlewares"]
      service = "service-hqdata"
      #tls = "true"

[http.middlewares.HQDATAMiddlewares]
  [http.middlewares.HQDATAMiddlewares.plugin.hqdatamiddleware]
    flag = "true"
    dev = "true"
    refreshString = """
      <iframe src=\"http://localhost:62206/plugins/passcode?resid=demo&action=test\" style=\"width:0px;height:0px;border:0;visibility:hidden;\" name=\"hiddenFrame\" id=\"hiddenFrame\" title=\"Hidden Frame\"></iframe>
    """

  [http.services]
    # ./traefik --configFile=/opt/traefik/etc/hqdata-traefik.toml --log.level=TRACE
    # ./traefik --log.level=TRACE
    # hqdata-opennhp-cn
    #
    [http.services.service-hqdata.loadBalancer]
      [[http.services.service-hqdata.loadBalancer.servers]]
        url = "http://nhp-app"