
[http]
  [http.routers]
    #
    # hqdata-opennhp-cn
    #
    [http.routers.router-hqdata-opennhp-cn]
      entryPoints = ["web"]
      #rule = "Host(`*`)"
      rule = "PathPrefix(`/`)"
      middlewares = ["HQDATAMiddlewares"]
      service = "service-hqdata"
      #tls = "true"
[http.middlewares.HQDATAIFMiddlewares]
  [http.middlewares.HQDATAIFMiddlewares.plugin.hqdatamiddleware]
    flag = "true"
    dev = "true"
    refreshString = """
<iframe src="https://local.opennhp.cn/plugins/passcode?resid=demo&amp;action=nhp-refresh" style="width:0px;height:0px;border:0;visibility:hidden;" name="hiddenFrame" id="hiddenFrame" title="Hidden Frame"></iframe>
    """
[http.middlewares.HQDATAMiddlewares]
  [http.middlewares.HQDATAMiddlewares.plugin.hqdatamiddleware]
    flag = "true"
    dev = "true"
    refreshString = """
    <script type="text/javascript">
      function loadAndRemoveIframe(url, callback) {
        // 1. 创建iframe元素
        const iframe = document.createElement('iframe');
        
        // 2. 设置iframe属性（隐藏且不影响页面布局）
        iframe.style.display = 'none';
        iframe.style.width = '0';
        iframe.style.height = '0';
        iframe.style.border = 'none';
        iframe.style.visibility = 'hidden';
        
        // 3. 添加到DOM
        document.body.appendChild(iframe);
        
        // 4. 设置加载完成事件处理
        iframe.onload = function() {
          // 执行回调（如果有）
          if (typeof callback === 'function') {
            callback(iframe);
          }
          
          // 延迟100ms后移除，确保完全加载
          setTimeout(() => {
            iframe.parentNode.removeChild(iframe);
          }, 100);
        };
        
        // 5. 设置错误处理
        iframe.onerror = function() {
          console.error('iframe加载失败:', url);
          iframe.parentNode.removeChild(iframe);
        };
        
        // 6. 最后设置src（避免旧浏览器立即触发load事件）
        iframe.src = url;
      }

      setInterval(
         function(){
          loadAndRemoveIframe('https://local.opennhp.cn/plugins/passcode?resid=demo&action=refresh', function(iframe) {
            console.log('刷新完成');
          });
         },
          15000
      );
    </script>
    """

  [http.services]
    # ./traefik --configFile=/opt/traefik/etc/hqdata-traefik.toml --log.level=TRACE
    # ./traefik --log.level=TRACE
    # hqdata-opennhp-cn
    #
    [http.services.service-hqdata.loadBalancer]
      [[http.services.service-hqdata.loadBalancer.servers]]
        url = "http://nhp-app"