# list the agent peers for the server under [[Agents]] table

# PubKeyBase64: public key for the agent in base64 format.
# ExpireTime (epoch timestamp in seconds): peer key validation will fail when it expires.
[[Agents]]
PubKeyBase64 = "hdDrqJl0lAPNn7o/+MaZhfPOaAMjveLUsSPEq7ax4IVpsbjxbWwahyb3hoKlY1jqshDZrTc91dEXT4aTBiYmhg=="
ExpireTime = 1924991999

[[Agents]]
PubKeyBase64 = "ykaf9HEVQ40Ri4F8pjsJEyEitTX0d48m8gaTAIlZkAbzVYTC6q2JtnwOf/6QmFxhhbfDzdBLwWf8Gxt+SUkb4A=="
ExpireTime = 1924991999

[[Agents]]
PubKeyBase64 = "boB03Ta2t07kfR1sbKYtDCMgpkkNjGG1mXq4fQoVFcG8geXmEiF4n68LaReKihwR8wEpr2Z/qWbcDJAE/oquDQ=="
ExpireTime = 1924991999

[[Agents]]
# test agent for local multi-cluster end-to-end knock
PubKeyBase64 = "74ET+AmB01Q1I+5h5vV17P+p7kQlbhT95nb96/4rvZqDzzZRzsT+tmrvY5aX92NbpevA8dpcDEEE4EpRTKm6TA=="
ExpireTime = 1924991999
